version: '3'
services:
  web:
    build: .
    image: halvong/crm
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: tom
      POSTGRES_DB: contact
    volumes:
      - .:/usr/src/app
  database:
    image: postgres
    ports:
      - "32772:5432"
    environment:
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: tom
      POSTGRES_DB: contact
    volumes:
      - db_data:/var/lib/postgresql/grandhotel_data
volumes:
  db_data: